### ISSUE TITLE
Dependencies 0.8.0 are incompatible between themself

### ISSUE THREAD

**Issue by kranfix** [rrousselGit/river_pod#109]
**Describe the bug**
`flutter_riverpod-0.8.0` and `hooks_riverpod-0.8.0` are incompatible with `riverpod-0.8.0`

**To Reproduce**

In a new project or in an exampl, add the following in the `pubspec.yaml`:
```yaml
dependencies:
  flutter:
    sdk: flutter
  riverpod: ^0.8.0
  flutter_riverpod: ^0.8.0
```

**Expected behavior**

The `flutter pub get` command should work.

**Solution**
Upgrading dependencies in `pubspec.yaml`.
In `flutter_riverpod`: upgrade `riverpod`
In `hooks_riverpod`: upgrde `riverpod` and `flutter_riverpod`.
