### ISSUE TITLE
riverpod migrate "Migrating git and path dependencies can cause issues because of trying to understand riverpod versioning, please depend on an official package"

### ISSUE THREAD

**Issue by imcouri** [rrousselGit/river_pod#1194]
I'm trying to migrate from 0.14.0+3 to version 1.0.0 using the migration tool but every time I run riverpod migrate I get this output and it stops.
`Migrating git and path dependencies can cause issues because of trying to understand riverpod versioning, please depend on an official package`

**Comment by imcouri** [comment]
its quite long 😅

```
name: App name
description: Description

publish_to: 'none' 


version: 12.5.5+8

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dio: ^4.0.0
  google_fonts: ^2.0.0
  hexcolor: ^2.0.6
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0
  flutter_secure_storage: ^4.2.0
  flutter_native_splash: ^1.1.8+4
  animated_background: ^2.0.0
  get: ^4.1.4
  cached_network_image: ^3.0.0
  bouncing_widget: ^2.0.0
  detectable_text_field: ^2.0.2
  flutter_inappwebview: ^5.3.2
  intl: ^0.17.0
  getwidget: ^2.0.3
  firebase_core: ^1.3.0
  google_sign_in: ^5.0.4
  firebase_auth: ^1.4.1
  shared_preferences: ^2.0.6
  flutter_chat_ui: ^1.3.0
  pinput: ^1.2.0
  flutter_countdown_timer: ^4.1.0
  awesome_dialog: ^2.1.0
  flutter_chat_types: ^3.0.0
  dart_ipify: ^1.1.0
  carousel_slider: ^4.0.0
  animations: ^2.0.1
  giphy_get: ^2.0.2
  image_picker:  ^0.8.2
  flutter_link_previewer: ^2.2.1
  youtube_player_iframe: ^2.2.2
  youtube_player_flutter: ^8.0.0
  timeago: ^3.1.0
  lazy_load_scrollview: ^1.3.0
  numeral: ^1.2.4
  like_button: ^2.0.2
  firebase_analytics: ^8.2.0
  firebase_remote_config: ^0.10.0+3
  video_player: ^2.1.13
  adaptive_dialog: ^1.1.0
  url_launcher: ^6.0.9
  flutter_launcher_icons: ^0.9.1
  screenshot: ^1.2.3
  path_provider: ^2.0.2
  http: ^0.13.3
  sign_in_with_apple: ^3.2.0
  flutter_video_info: ^1.2.0
  chewie:
    git:
      url: git://github.com/imcouri/chewie.git
      ref: master
  profanity_filter: ^2.0.0
  firebase_dynamic_links: ^2.0.9
  firebase_messaging: ^10.0.7
  share_plus: ^2.1.4
  lottie: ^1.1.0
  version: ^2.0.0
  platform_device_id: ^1.0.1
  in_app_notification: ^1.0.1
  percent_indicator: ^3.4.0
  holding_gesture: ^1.1.0
  aesthetic_dialogs: ^0.0.14+3
  flutter_advanced_drawer: ^1.2.4
  shimmer_animation: ^2.1.0+1
  confetti: ^0.6.0
  animated_text_kit: ^4.2.1
  animate_do: ^2.0.0
  vibration: ^1.7.4-nullsafety.0
  multiavatar: ^0.1.5
  flutter_svg: ^0.22.0
  google_mobile_ads: ^0.13.3
  native_admob_flutter: ^1.5.0
  app_tracking_transparency: ^2.0.1
  uuid: ^3.0.4
  flutter_webview_plugin:
    git:
      url: git://github.com/jiankian/flutter_webview_plugin.git
      ref: master
  webview_flutter: ^2.0.12
  cool_dropdown: ^1.2.0
  flutter_staggered_grid_view: ^0.4.1
  flex_color_picker: ^2.1.2
  notification_permissions: ^0.6.1
  translator: ^0.1.7
  language_picker: ^0.4.1
  platform: ^3.1.0
  supabase: ^0.2.10
  postgrest: ^0.1.5
  realtime_client: ^0.1.9
  flutter_riverpod: ^0.14.0



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/IosIcon.jpg"


flutter:


  uses-material-design: true

  assets:
    - assets/images/
```
