### ISSUE TITLE
[Bug] About dependencies

### ISSUE THREAD

**Issue by shinriyo** [rrousselGit/river_pod#32]
**Describe the bug**

it is happened.
```
Running "flutter pub upgrade" in my_app...                      

Because hooks_riverpod >=0.1.0 depends on flutter_hooks ^0.10.0 and my_app depends on flutter_hooks ^0.11.0, hooks_riverpod >=0.1.0 is forbidden.
So, because my_app depends on hooks_riverpod ^0.3.0, version solving failed.
pub upgrade failed (1; So, because my_app depends on hooks_riverpod ^0.3.0, version solving failed.)
```

**To Reproduce**

Modify `pubspec.yaml` below and excute `flutter pub upgrade`.

```
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">= 1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_hooks: ^0.11.0
  hooks_riverpod: ^0.3.0
```

<Please add a small sample to that can be executed to reproduce the problem. As a general rule, 100 lines is the maximum>

it is about `yaml`. So, no code.

**Expected behavior**

downgrade flutter_hooks works, but it opponents for document.
```
  # flutter_hooks: ^0.11.0
  flutter_hooks: ^0.10.0
  hooks_riverpod: ^0.3.0
```
