### ISSUE TITLE
Basic example type errors

### ISSUE THREAD

**Issue by rhyek** [rrousselGit/river_pod#430]
Totally new to flutter, especially riverpod. Using hooks, with a state notifier provider declared like so:
```dart
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:mobile_app/models/adder.dart';

final drinkEventProvider = StateNotifierProvider((ref) => DrinkEventNotifier());

class DrinkEventNotifier extends StateNotifier<List<DrinkEvent>> {
  DrinkEventNotifier() : super([]);

  void add(Adder adder) {
    var adderCopy = Adder(adder.label, adder.amount);
    var event = DrinkEvent(adderCopy);
    state = [...state, event];
  }

  void removeLast() {
    state = state.take(state.length - 1).toList();
  }
}
```
I have a home widget declared like so:
```dart
class Home extends HookWidget {
  final String title;

  Home({Key key, this.title}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final drinkEvents = useProvider(drinkEventProvider);
   ...etc
```

`drinkEvents` in that case is typed as `dynamic` where I would expect it to be `List<DrinkEvent>`. If I try to see `useProvider`'s result I can see this (no `state` property):
![image](https://user-images.githubusercontent.com/702922/114314485-25934300-9ab8-11eb-8c95-f9bdc8e4045f.png)

Then, trying to access any of `DrinkEventNotifier`'s methods (`add`, `removeLast`):

![image](https://user-images.githubusercontent.com/702922/114314593-99355000-9ab8-11eb-99cb-0d8d8cd17ee4.png)

pubspec.yaml:
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  duration: ^3.0.6
  intl: ^0.17.0
  hooks_riverpod: ^0.14.0+1
  flutter_hooks: ^0.16.0
```
