### ISSUE TITLE
Error in release mode: "Cannot call ProviderSubscription.flush() after close was called"

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [rrousselGit/river_pod#485]
**Describe the bug**

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Bad state: Cannot call ProviderSubscription.flush() after close was called
#0      ProviderSubscription.flush (package:riverpod/src/framework/base_provider.dart:424)
#1      ProviderElement.flush (package:riverpod/src/framework/base_provider.dart:602)
#2      ProviderContainer.readProviderElement (package:riverpod/src/framework/container.dart:352)
#3      ProviderContainer._disposeProvider (package:riverpod/src/framework/container.dart:212)
#4      _AutoDisposer._performDispose (package:riverpod/src/framework/auto_dispose.dart:128)
#5      _AutoDisposer.scheduleDispose.<anonymous closure> (package:riverpod/src/framework/auto_dispose.dart:104)
#6      new Future.microtask.<anonymous closure> (dart:async/future.dart:198)
#7      _rootRun (dart:async/zone.dart:1420)
#8      _CustomZone.run (dart:async/zone.dart:1328)
#9      _CustomZone.runGuarded (dart:async/zone.dart:1236)
#10     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#11     _rootRun (dart:async/zone.dart:1428)
#12     _CustomZone.run (dart:async/zone.dart:1328)
#13     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)
```

**To Reproduce**

This is a difficult one. The only insight about htis error I have right now is that it happens in release mode only.

I am not sure how to debug this. @rrousselGit if you have any idea how I could debug this, please let me know.

Here is what I observe:

* In debug mode, I do action A and then action B in my app - everything looks good (empty console).
* In release mode, I do action A and then action B (**exact same steps**) and then the above error is thrown and it looks like particular `ConsumerWidget`s are affected initially (gray error widget). On interaction, this happens to the whole app.

I am feeling a bit dumb here with the reproduction steps, but I am not sure how to further debug this. It looks like my code is all good and this is a release mode problem with (`flutter_`)`riverpod`.

```
flutter_riverpod:
    dependency: "direct main"
    description:
      name: flutter_riverpod
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.0+1"
riverpod:
    dependency: transitive
    description:
      name: riverpod
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.0+1"
```
