### ISSUE TITLE
[web] using hooks_riverpod app stuck at `Waiting for connection from debug service on Chrome...`

### ISSUE THREAD

**Issue by aoatmon** [rrousselGit/river_pod#897]
**Describe the bug**
using `hooks_riverpod` `1.0.0` on web cause the app to be stack at 
` "Waiting for connection from debug service on Chrome..." `

**To Reproduce**

<details>
  <summary>code sample</summary>
  
```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'pod.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends HookConsumerWidget {
  final String title;
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  @override
  Widget build(context, ref) {
    final counter = ref.watch(counterPod);
    return Scaffold(
      appBar: AppBar(title: Text(title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text('You have pushed the button this many times:'),
            Text(
              '${counter.value}',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => counter.value = counter.value++,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

```

</details>

<details>
  <summary>pubspec.yaml</summary>
  
```yaml
name: counter_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
```

</details>
